name: Request Copilot Review on Dependabot PRs

on:
  pull_request:
    types: [opened, reopened]
    branches: [ main ]

permissions:
  pull-requests: write

jobs:
  request-copilot-review:
    runs-on: ubuntu-latest
    # Only run for Dependabot PRs (check PR author, not who triggered the event)
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    
    steps:
      - name: Request Copilot review
        uses: actions/github-script@v7
        with:
          script: |
            // GitHub Copilot reviews are triggered by comments, not reviewer assignments
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '@github-copilot review'
            });
            console.log('✅ Copilot review requested via comment');
